# Administrative Section Blacklist
# Generated by filter_admin_sections.py
#
# Usage in extractors:
#   from admin_blacklist import ADMIN_SECTION_PATTERNS
#   if any(re.match(p, heading, re.I) for p in ADMIN_SECTION_PATTERNS):
#       skip_this_chunk()

import re

ADMIN_SECTION_PATTERNS = [
    r'^ethics?\s*(approval|statement|review)?$',
    r'^consent\s*(for\s*publication|statement)?$',
    r'^institutional\s*review\s*board',
    r'^irb\s*approval',
    r'^author[\'s]?\s*contributions?$',
    r'^author[\'s]?\s*information',
    r'^authors?.*contributions?',
    r'^acknowledgeme?nts?$',
    r'^footnotes?$',
    r'^conflicts?\s*of\s*interests?$',
    r'^competing\s*interests?$',
    r'^disclosure',
    r'^financial\s*disclosure',
    r'^data\s*availability\s*statement',
    r'^availability\s*of\s*data',
    r'^associated\s*data$',
    r'^supplementary\s*(materials?|information|data|figures?|tables?)',
    r'^electronic\s*supplementary',
    r'^additional\s*files?',
    r'^funding\s*statement',
    r'^funding\s*information',
    r'^funding$',
    r'^financial\s*support',
    r'^grants?$',
    r'^copyright',
    r'^open\s*access',
    r'^abbreviations?$',
    r'^publisher.*note',
    r'^received:',
    r'^accepted:',
    r'^published:',
    r'^(figure|table|fig\.)\s*\d+\s*(legend|caption)',
]

ADMIN_PATTERNS_COMPILED = [re.compile(p, re.IGNORECASE) for p in ADMIN_SECTION_PATTERNS]

def is_admin_section(heading: str) -> bool:
    if not heading:
        return False
    for pattern in ADMIN_PATTERNS_COMPILED:
        if pattern.search(heading.strip()):
            return True
    return False
